# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
