# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171119_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
