import keyMirror from 'key-mirror';

export default keyMirror({
  /* Auth */
  SET_INTL_DATA: null,
  INIT_LOCALE: null,
  LOCALE_CONFIG_REQUEST: null,
  LOCALE_CONFIG_SUCCESS: null,
  LOCALE_CONFIG_FAILURE: null,
  LOCALE_SET_LANGUAGE_REQUEST: null,
  LOCALE_SET_LANGUAGE_SUCCESS: null,
  LOCALE_SET_LANGUAGE_FAILURE: null,
  DELETE_SESSIONTOKEN_REQUEST: null,
  DELETE_SESSIONTOKEN_SUCCESS: null,
  DELETE_SESSIONTOKEN_FAILURE: null,
  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNIN: null,
  SIGNIN_STATEFORM: null,
  SIGNIN_REQUEST: null,
  SIGNIN_SUCCESS: null,
  SIGNIN_FAILURE: null,
  SIGNUP: null,
  SIGNUP_STATEFORM: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,
  LOGOUT: null,
  LOGOUT_STATEFORM: null,
  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,
  RESET_PASSWORD: null,
  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,
  FORGOT_PASSWORD: null,
  FORGOT_PASSWORD_STATEFORM: null,
  /* Modal */
  SHOW_MODAL: null,
  HIDE_MODAL: null,
  DESTROY_MODAL: null,
  /* USER */
  CHANGETHEME: null,
  /* Alert */
  SHOW_ALERT: null,
  HIDE_ALERT: null,
  /* Dropzone */
  SAVE_FILE: null,
  /* PanelDropdown */
  SHOW_ITEMS: null,
  HIDE_ITEMS: null,
  SET_IS_ACTIVE: null,
  TOGGLE_ITEMS: null
});
